---
- name: Configuraci칩n avanzada con usuario y Docker
  hosts: localhost
  become: true
  tasks:
    - name: Crear usuario "deploy"
      user:
        name: deploy
        password: "{{ 'mipassword123' | password_hash('sha512') }}"
        shell: /bin/bash
        state: present
        create_home: yes

    - name: Instalar dependencias para Docker
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common

    - name: A침adir GPG key de Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: A침adir repositorio de Docker
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Instalar Docker
      apt:
        name: docker-ce
        state: present
        update_cache: yes

    - name: A침adir usuario "deploy" al grupo docker
      user:
        name: deploy
        groups: docker
        append: yes

    - name: Iniciar y habilitar Docker
      service:
        name: docker
        state: started
        enabled: true
